/config/device_registration/{device_registration_id}:
  delete:
    description: Remove an item
    operationId: api.v1.Config::DeviceRegistrations.remove
    parameters: []
    responses:
      '204':
        description: Deleted a config item
  description: pf::UnifiedApi::Controller::Config::DeviceRegistrations
  get:
    description: Get an item
    operationId: api.v1.Config::DeviceRegistrations.get
    parameters: []
    responses:
      '200':
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/config/DeviceRegistration'
      '400':
        $ref: '#/components/responses/BadRequest'
      '422':
        $ref: '#/components/responses/UnprocessableEntity'
  patch:
    description: Update an item
    operationId: api.v1.Config::DeviceRegistrations.update
    parameters: []
    requestBody:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/config/DeviceRegistration'
    responses:
      '400':
        $ref: '#/components/responses/BadRequest'
      '422':
        $ref: '#/components/responses/UnprocessableEntity'
  put:
    description: Replace an item
    operationId: api.v1.Config::DeviceRegistrations.replace
    parameters: []
    requestBody:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/config/DeviceRegistration'
    responses:
      '201':
        $ref: '#/components/responses/Created'
      '400':
        $ref: '#/components/responses/BadRequest'
      '422':
        $ref: '#/components/responses/UnprocessableEntity'
