/config/floating_device/{floating_device_id}:
  delete:
    description: Remove an item
    operationId: api.v1.Config::FloatingDevices.remove
    parameters: []
    responses:
      '204':
        description: Deleted a config item
  description: Configure floating devices
  get:
    description: Get an item
    operationId: api.v1.Config::FloatingDevices.get
    parameters: []
    responses:
      '200':
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/config/FloatingDevice'
      '400':
        $ref: '#/components/responses/BadRequest'
      '422':
        $ref: '#/components/responses/UnprocessableEntity'
  patch:
    description: Update an item
    operationId: api.v1.Config::FloatingDevices.update
    parameters: []
    requestBody:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/config/FloatingDevice'
    responses:
      '400':
        $ref: '#/components/responses/BadRequest'
      '422':
        $ref: '#/components/responses/UnprocessableEntity'
  put:
    description: Replace an item
    operationId: api.v1.Config::FloatingDevices.replace
    parameters: []
    requestBody:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/config/FloatingDevice'
    responses:
      '201':
        $ref: '#/components/responses/Created'
      '400':
        $ref: '#/components/responses/BadRequest'
      '422':
        $ref: '#/components/responses/UnprocessableEntity'
