/config/portal_modules:
  description: pf::UnifiedApi::Controller::Config::PortalModules
  get:
    description: List items
    operationId: api.v1.Config::PortalModules.list
    parameters: []
    responses:
      '200':
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/config/PortalModulesList'
      '400':
        $ref: '#/components/responses/BadRequest'
      '422':
        $ref: '#/components/responses/UnprocessableEntity'
