/config/source/{source_id}:
  delete:
    description: Remove an item
    operationId: api.v1.Config::Sources.remove
    parameters: []
    responses:
      '204':
        description: Deleted a config item
  description: pf::UnifiedApi::Controller::Config::Sources
  get:
    description: Get an item
    operationId: api.v1.Config::Sources.get
    parameters: []
    responses:
      '200':
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/config/Source'
      '400':
        $ref: '#/components/responses/BadRequest'
      '422':
        $ref: '#/components/responses/UnprocessableEntity'
  patch:
    description: Update an item
    operationId: api.v1.Config::Sources.update
    parameters: []
    requestBody:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/config/Source'
    responses:
      '400':
        $ref: '#/components/responses/BadRequest'
      '422':
        $ref: '#/components/responses/UnprocessableEntity'
  put:
    description: Replace an item
    operationId: api.v1.Config::Sources.replace
    parameters: []
    requestBody:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/config/Source'
    responses:
      '201':
        $ref: '#/components/responses/Created'
      '400':
        $ref: '#/components/responses/BadRequest'
      '422':
        $ref: '#/components/responses/UnprocessableEntity'
