/config/switches:
  description: pf::UnifiedApi::Controller::Config::Switches
  get:
    description: List items
    operationId: api.v1.Config::Switches.list
    parameters: []
    responses:
      '200':
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/config/SwitchesList'
      '400':
        $ref: '#/components/responses/BadRequest'
      '422':
        $ref: '#/components/responses/UnprocessableEntity'
