/config/violations:
  description: pf::UnifiedApi::Controller::Config::Violations
  get:
    description: List items
    operationId: api.v1.Config::Violations.list
    parameters: []
    responses:
      '200':
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/config/ViolationsList'
      '400':
        $ref: '#/components/responses/BadRequest'
      '422':
        $ref: '#/components/responses/UnprocessableEntity'
