#!/bin/sh

LOGFILE=/usr/local/pf/logs/a3_update.log
TMPDIR=`/usr/bin/mktemp -d -p /tmp a3_update.XXXXXXXX`

if [ $? -ne 0 ]; then
    echo "Unable to create workspace for update" >> $LOGFILE
    exit 1
fi

/usr/local/pf/sbin/a3_update $TMPDIR

# Be sure to clean up lock file
/usr/bin/rm -f /usr/local/pf/var/run/update.lock

# Be sure to remove tmpdir
/usr/bin/rm -rf $TMPDIR
