#!/usr/bin/perl

=head1 NAME

pfunified_api

=cut

=head1 DESCRIPTION

pfunified_api

=cut

use strict;
use warnings;
use lib qw(/usr/local/pf/lib);
use Mojolicious::Commands;

# Start command line interface for application
Mojolicious::Commands->start_app('pf::UnifiedApi::custom');


=head1 AUTHOR

Inverse inc. <info@inverse.ca>

=head1 COPYRIGHT

Copyright (C) 2005-2018 Inverse inc.

=cut

