openapi: "3.0.0"

info:
  title: A3 API
  description: An API to access the A3 resources. Lets make the A3 API great again!
  version: 0.0.1

paths: {}

components: {}

servers:
  - url: https://127.0.0.1:9999/api/v1

security:
  - bearerAuth: []
